services:
  - type: web
    name: storage
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.app:app
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
